# Basics of NumPy and Matplotlib

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Basic concepts in analysis

In [2]:
# Creating sequences as arrays
# 100 evenly spaced values from 0 to 5
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [3]:
# (a_n) = 3,4,5, ..99
a_n = np.arange(3, 100)

In [5]:
# (b_n) = 3, 5, 7,...99
b_n = np.arange(3,99.1,2)

In [6]:
# (c_n) = 1/3, sqrt(2), pi
c_n = np.array([1/3, np.sqrt(2), np.pi])

In [7]:
# (d_n) = 100 terms, all 0
d_n = np.zeros(100)

In [8]:
# (e_n) = 100 terms, all 0.7
e_n = np.full(100, 0.7)

In [9]:
# Array operations
# Addition and scalar multiplication
# (x_n) = (2a_n - 5)
x_n = 2 * a_n - 5
x_n

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193])

In [10]:
# (y_n) = (a_n + x_n)
y_n = a_n + x_n
y_n

array([  4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,  40,
        43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,  79,
        82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115, 118,
       121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154, 157,
       160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196,
       199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232, 235,
       238, 241, 244, 247, 250, 253, 256, 259, 262, 265, 268, 271, 274,
       277, 280, 283, 286, 289, 292])

In [11]:
# Multiplication and division
# (x_n * y_n)
z_n = x_n * y_n
z_n


array([    4,    21,    50,    91,   144,   209,   286,   375,   476,
         589,   714,   851,  1000,  1161,  1334,  1519,  1716,  1925,
        2146,  2379,  2624,  2881,  3150,  3431,  3724,  4029,  4346,
        4675,  5016,  5369,  5734,  6111,  6500,  6901,  7314,  7739,
        8176,  8625,  9086,  9559, 10044, 10541, 11050, 11571, 12104,
       12649, 13206, 13775, 14356, 14949, 15554, 16171, 16800, 17441,
       18094, 18759, 19436, 20125, 20826, 21539, 22264, 23001, 23750,
       24511, 25284, 26069, 26866, 27675, 28496, 29329, 30174, 31031,
       31900, 32781, 33674, 34579, 35496, 36425, 37366, 38319, 39284,
       40261, 41250, 42251, 43264, 44289, 45326, 46375, 47436, 48509,
       49594, 50691, 51800, 52921, 54054, 55199, 56356])

In [12]:
# ( 2/x_n)
w_n = 2/x_n
w_n

array([2.        , 0.66666667, 0.4       , 0.28571429, 0.22222222,
       0.18181818, 0.15384615, 0.13333333, 0.11764706, 0.10526316,
       0.0952381 , 0.08695652, 0.08      , 0.07407407, 0.06896552,
       0.06451613, 0.06060606, 0.05714286, 0.05405405, 0.05128205,
       0.04878049, 0.04651163, 0.04444444, 0.04255319, 0.04081633,
       0.03921569, 0.03773585, 0.03636364, 0.03508772, 0.03389831,
       0.03278689, 0.03174603, 0.03076923, 0.02985075, 0.02898551,
       0.02816901, 0.02739726, 0.02666667, 0.02597403, 0.02531646,
       0.02469136, 0.02409639, 0.02352941, 0.02298851, 0.02247191,
       0.02197802, 0.02150538, 0.02105263, 0.02061856, 0.02020202,
       0.01980198, 0.01941748, 0.01904762, 0.01869159, 0.01834862,
       0.01801802, 0.01769912, 0.0173913 , 0.01709402, 0.01680672,
       0.01652893, 0.01626016, 0.016     , 0.01574803, 0.01550388,
       0.01526718, 0.01503759, 0.01481481, 0.01459854, 0.01438849,
       0.0141844 , 0.01398601, 0.0137931 , 0.01360544, 0.01342

In [13]:
# (x_n/y_n)
v_n = x_n/y_n
v_n

array([0.25      , 0.42857143, 0.5       , 0.53846154, 0.5625    ,
       0.57894737, 0.59090909, 0.6       , 0.60714286, 0.61290323,
       0.61764706, 0.62162162, 0.625     , 0.62790698, 0.63043478,
       0.63265306, 0.63461538, 0.63636364, 0.63793103, 0.63934426,
       0.640625  , 0.64179104, 0.64285714, 0.64383562, 0.64473684,
       0.64556962, 0.64634146, 0.64705882, 0.64772727, 0.64835165,
       0.64893617, 0.64948454, 0.65      , 0.65048544, 0.6509434 ,
       0.65137615, 0.65178571, 0.65217391, 0.65254237, 0.65289256,
       0.65322581, 0.65354331, 0.65384615, 0.65413534, 0.65441176,
       0.65467626, 0.65492958, 0.65517241, 0.65540541, 0.65562914,
       0.65584416, 0.65605096, 0.65625   , 0.65644172, 0.65662651,
       0.65680473, 0.65697674, 0.65714286, 0.65730337, 0.65745856,
       0.6576087 , 0.65775401, 0.65789474, 0.65803109, 0.65816327,
       0.65829146, 0.65841584, 0.65853659, 0.65865385, 0.65876777,
       0.6588785 , 0.65898618, 0.65909091, 0.65919283, 0.65929

In [14]:
# Exponentiation
# (x_n^3)
u_n = x_n**3
u_n

array([      1,      27,     125,     343,     729,    1331,    2197,
          3375,    4913,    6859,    9261,   12167,   15625,   19683,
         24389,   29791,   35937,   42875,   50653,   59319,   68921,
         79507,   91125,  103823,  117649,  132651,  148877,  166375,
        185193,  205379,  226981,  250047,  274625,  300763,  328509,
        357911,  389017,  421875,  456533,  493039,  531441,  571787,
        614125,  658503,  704969,  753571,  804357,  857375,  912673,
        970299, 1030301, 1092727, 1157625, 1225043, 1295029, 1367631,
       1442897, 1520875, 1601613, 1685159, 1771561, 1860867, 1953125,
       2048383, 2146689, 2248091, 2352637, 2460375, 2571353, 2685619,
       2803221, 2924207, 3048625, 3176523, 3307949, 3442951, 3581577,
       3723875, 3869893, 4019679, 4173281, 4330747, 4492125, 4657463,
       4826809, 5000211, 5177717, 5359375, 5545233, 5735339, 5929741,
       6128487, 6331625, 6539203, 6751269, 6967871, 7189057])

In [15]:
# (3^x_n)
t_n = 3**x_n
t_n

array([                   3,                   27,                  243,
                       2187,                19683,               177147,
                    1594323,             14348907,            129140163,
                 1162261467,          10460353203,          94143178827,
               847288609443,        7625597484987,       68630377364883,
            617673396283947,     5559060566555523,    50031545098999707,
         450283905890997363,  4052555153018976267,  -420491770248316829,
       -3784425932234851461,  2833654757305440083,  7056148742039409131,
        8165106457226027331,  -301018179803960485, -2709163618235644365,
       -5935728490411247669,  1918675807427425827, -1178661806862719173,
        7838787811945079059, -3237885987332494933,  7752514261426648835,
       -4014347941998366949,   764356669433800691,  6879210024904206219,
        6572658003009201123,  3813689805954155259, -2570279893831705901,
       -4685774970775801493, -5278486589563110205, 

In [16]:
# Other useful commands
# The number of elements in an array x_n
len(x_n)

97

In [17]:
# Shape of the array
x_n.shape

(97,)

In [18]:
# Calling elements of (x_n) by its index
# The first element
x_n[0]

1

In [19]:
# The fifth element
x_n[4]

9

In [20]:
# The last element
x_n[-1]

193

In [21]:
# The first 9 elements (slicing)
x_n[0:9]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [23]:
# (z_n) = zero array, shame shape as x_n
z_n = np.zeros_like(x_n)

In [27]:
# (w_n) = array of 0.7, same shape as x_n
w_n = np.full_like(x_n, 0.7)

In [28]:
w_n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
z_n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

## Series

In [30]:
# Series evaluation
# The sum from 1 to 100
x = np.arange(1,101)
sum(x)

5050

In [31]:
# The sum of n X (n + 3) from n = 1 to 100
x@(x+3)

353500

## Functions

In [32]:
# defining lambda funcions
F = lambda x: 2 * x + 1
G = lambda x,y : x + y

In [33]:
G(1,2)

3

In [34]:
F(5)

11

In [35]:
# Another way of defining functions
def F(x):
    return 2*x + 1

In [36]:
F(5)

11

### Finding N given e

In [38]:
# For any given e, say, 10-5
epsilon = 1e-5
n = 1
err = np.e - (1 + 1/n)**n
# Continue searching until the error < e
# Increasing n by 1 per iteration
while err >= epsilon:
    n += 1
    err = np.e - (1 + 1/n)**n

print("N_min = ", n - 1)

N_min =  135912
